# Book settings
title: demandBeats
author: World Bank Development Data Group
logo: docs/images/logo.png

repository:
    url: https://github.com/worldbank/template
    branch: main

html:
    home_page_in_navbar: false
    extra_navbar: ""
    use_edit_page_button: true
    use_repository_button: true
    use_issues_button: true
    baseurl: https://worldbank.github.io/template

only_build_toc_files: true

model:
  kwargs:
    horizon: 3
  name: Nbeats
paths:
  dataPath: data/target
  driversPath: data/driver
  forecastResultPath: data/forecast
  rootPath: data/
  backtestingPath: data/backtest
target:
  abbr: Platinum_spot_price
  displayName: Platinum
  filter_column: 12
  frequency: MS